<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Introduction to numpy:
</p><br>

<p style="font-family: Arial; font-size:1.25em;color:#2462C0; font-style:bold"><br>
Package for scientific computing with Python
</p><br>

Numerical Python, or "Numpy" for short, is a foundational package on which many of the most common data science packages are built.  Numpy provides us with high performance multi-dimensional arrays which we can use as vectors or matrices.  

The key features of numpy are:

- ndarrays: n-dimensional arrays of the same data type which are fast and space-efficient.  There are a number of built-in methods for ndarrays which allow for rapid processing of data without using loops (e.g., compute the mean).
- Broadcasting: a useful tool which defines implicit behavior between multi-dimensional arrays of different sizes.
- Vectorization: enables numeric operations on ndarrays.

<b>Additional Recommended Resources:</b><br>
<a href="https://docs.scipy.org/doc/numpy/reference/">Numpy Documentation</a><br>




<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Getting started with ndarray<br><br></p>

**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy.  Like the data structures, let's get started by creating ndarrays using the numpy package.

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create Rank 1 numpy arrays:
</p>

### Installing numpy package through pip and conda

In [1]:
!pip install numpy -y

You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
!pip install --upgrade pip

     |████████████████████████████████| 1.4MB 1.5MB/s eta 0:00:01
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1


In [1]:
import numpy as np

## Creating 1-D array

In [8]:
l = [1,2,3,4,5]
arr = np.array(l)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [4]:
type(l)

list

In [9]:
# test the shape of the array we just created, it should have just one dimension (Rank 1)
print(arr.shape) #(5,)

(5,)


In [5]:
# because this is a 1-rank array, we need only one index to accesss each element
print(arr[0], arr[1], arr[2]) 

1 2 3


In [6]:
arr[0] = 8           # ndarrays are mutable, here we change an element of the array
print(arr)

[8 2 3 4 5]


In [5]:
arr1 = np.array(["1",2.0,1])  # np.arrays are homogeneous in nature 
print(arr1)

[1. 2. 1.]


In [ ]:
#int
#float
#string

In [4]:
type(arr1[1])

numpy.str_

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

How to create a Rank 2 numpy array:</p>

A rank 2 **ndarray** is one with two dimensions.  Notice the format below of [ [row] , [row] ].  2 dimensional arrays are great for representing matrices which are often useful in data science.

In [6]:
l1 = [[1,2,3],
      [4,5,6],
      [7,8,3],
     [1,2,3]]

1 Dimension: <In 1darray how many values I have>
2 Dimension: <number of 1darray's>, <In 1darray how many values I have>
3 Dimension: <number of 2darray's>, <number of 1darray's>, <In 1darray how many values I have>
4 Dimension: <number of 3darray's>, <number of 2darray's>, <number of 1darray's>, <In 1darray how many values I have>

In [7]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,3]

l1 = [[[1,2,3],[1,2,3],[1,2,3]],[a,b,c],[a,b,c]]
print(l1)

In [8]:
print(np.array(l1))

[[1 2 3]
 [4 5 6]
 [7 8 3]
 [1 2 3]]


In [10]:
arr_twod = np.array(l1)   # Create a rank 2 array

print(arr_twod)  # print the array

print("The shape is rows, columns: ", arr_twod.shape)  # rows x columns                   

print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ", arr_twod[0, 0], ", ",arr_twod[0, 1],", ", arr_twod[1, 0])

[[1 2 3]
 [4 5 6]
 [7 8 3]
 [1 2 3]]
The shape is rows, columns:  (4, 3)
Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  1 ,  2 ,  4


In [20]:
np.random.seed(875)

In [ ]:
#Random Uniform Distribution : rand(standard 0 - 1) and uniform(You can give the range)
#Random Normal Distribution: randn(mean 0 SD 1) and normal (you can pass mean and SD)

#Random Integers: randint(you can pass the range)

In [34]:
# create an array of random floats between 0 and 1
ex5 = np.random.rand(2,3,3)  # Random numbers from a uniform distribution between 0 & 1
print(ex5)

[[[0.72716669 0.6432094  0.26488961]
  [0.18810199 0.53129243 0.91474156]
  [0.88117158 0.84941195 0.57976844]]

 [[0.71403435 0.00410734 0.19682427]
  [0.16945771 0.75175242 0.74764778]
  [0.20988397 0.05610339 0.68478015]]]


In [35]:
a1 = np.random.uniform(1,10,(2,2,2))  # Random numbers from a uniform distribution between given range low=1, high=10
print(a1)

[[[5.67410449 9.88274359]
  [3.61094969 4.76798957]]

 [[2.76253974 6.39459481]
  [2.78256844 1.83143543]]]


In [29]:
ex6 = np.random.randn(3,3) # Random numbers from a standard normal distribution mean=0, SD=1
print(ex6)

[[-0.53987907  0.70816002  0.84222474]
 [ 0.2035808   2.39470366  0.91745894]
 [-0.11227247 -0.36218045 -0.23218226]]


In [11]:
a2 = np.random.normal(0,3,(2,2))  # Random numbers from a normal distribution between given range mean=0, SD=3
print(a2)

[[ 3.85646337  3.96880259]
 [ 1.9585636  -0.64685467]]


In [20]:
ex7 = np.random.randint(1,100,(2,2))  # generate random integers numbers in the given range
print(ex7)

[[79 40]
 [31 52]]


In [21]:
ex8 = np.random.randint(1,100,(3,3)) # generate random integers numbers in the given range for specified shape
print(ex8)


[[64 49 76]
 [53  5 55]
 [57 39 79]]


### Exercise 1 : Genearte a list of 20 random samples for a dice throw 

In [39]:
dice_samples = np.random.randint(1,7,20)
print(dice_samples)

[3 1 1 2 4 1 6 4 5 6 4 1 6 6 2 4 4 2 4 4]


# Basics of NumPy Arrays

## * Attributes of arrays
## * Indexing of arrays
## * Slicing of arrays
## * Reshaping of arrays


# 1. Attributes of Arrays: 
### Determining the size, shape, data type and dimension of array

In [40]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [41]:
print('X1 array is : ' ,x1)
print('**********')
print('X2 array is : ', x2)
print('**********')
print('X3 array is : ')
print(x3)

X1 array is :  [0 8 8 9 1 6]
**********
X2 array is :  [[7 5 4 8]
 [5 6 0 2]
 [5 1 5 8]]
**********
X3 array is : 
[[[9 9 3 2 0]
  [5 5 1 9 2]
  [3 3 7 1 9]
  [0 1 2 2 5]]

 [[6 0 3 5 0]
  [9 9 8 4 6]
  [9 2 1 7 4]
  [7 9 0 7 8]]

 [[5 3 6 6 8]
  [7 5 7 1 2]
  [9 8 4 0 8]
  [2 5 1 3 5]]]


In [26]:
print("dimension of x1 : ", x1.ndim)
print("Shape of x1 : ", x1.shape)
print("size of x1 : ", x1.size)
print("data type of x1 : ", x1.dtype)

dimension of x1 :  1
Shape of x1 :  (6,)
size of x1 :  6
data type of x1 :  int64


In [11]:
print("dimension of x2 : ", x2.ndim)
print("Shape of x2 : ", x2.shape)
print("size of x2 : ", x2.size)
print("data type of x2 : ", x2.dtype)

dimension of x2 :  2
Shape of x2 :  (3, 4)
size of x2 :  12
data type of x2 :  int64


In [10]:
print("dimension of x3 : ", x3.ndim)
print("Shape of x3 : ", x3.shape)
print("size of x3 : ", x3.size)
print("data type of x3 : ", x3.dtype)

dimension of x3 :  3
Shape of x3 :  (3, 4, 5)
size of x3 :  60
data type of x3 :  int64


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>

Array Indexing
<br><br></p>

In [52]:
P = np.array([[11,12,15,15], [21,22,47,17], [18,45,68,98]], dtype='int32')
print(P)
P.shape

[[11 12 15 15]
 [21 22 47 17]
 [18 45 68 98]]


(3, 4)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Normal indexing:
</p>

We can use rows and cols index values to retrieve any element. 

In [18]:
P[1,2]

47

In [22]:
print(x3)

[[[7 8 9 8 4]
  [0 5 3 7 5]
  [1 1 3 1 7]
  [9 6 1 9 7]]

 [[9 1 0 8 6]
  [1 5 1 8 1]
  [2 3 3 8 7]
  [2 5 7 0 8]]

 [[1 1 0 3 7]
  [1 9 5 3 3]
  [1 5 2 1 6]
  [5 6 8 4 5]]]


In [25]:
x3[1,0,0]

9

In [53]:
P[1,2] = 50  # Normal indexing fetching an element present at the location 2,2

In [54]:
P

array([[11, 12, 15, 15],
       [21, 22, 50, 17],
       [18, 45, 68, 98]], dtype=int32)

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Slice indexing:
</p>

Similar to the use of slice indexing with lists and strings, we can use slice indexing to pull out sub-regions of ndarrays.

Use array slicing to get a subarray consisting of the first 2 rows x 2 columns.

In [55]:
print(P)

[[11 12 15 15]
 [21 22 50 17]
 [18 45 68 98]]


In [56]:
p_slice = P[0:2,1:3].copy()
print(p_slice)
print(p_slice.shape)

[[12 15]
 [22 50]]
(2, 2)


In [48]:
print(p_slice[0,0],p_slice[1,1])

12 50


In [57]:
p_slice[0,0] = 24
p_slice

array([[24, 15],
       [22, 50]], dtype=int32)

In [58]:
P

array([[11, 12, 15, 15],
       [21, 22, 50, 17],
       [18, 45, 68, 98]], dtype=int32)

In [39]:
a_slice = P[0:1].copy()   # Creates a explicit copy
a_slice[0,0]=1000
print(P)
print(a_slice)

[[11 12 60 15]
 [21 22 47 17]
 [18 45 68 98]]

[[1000   12   60   15]]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Use both normal indexing & slice indexing
</p>

We can use combinations of integer scalar and slice indexing to create different shaped matrices.

In [59]:
# Create a Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [36]:
# Using both integer scalar & slicing generates an array of lower rank
row_rank1 = an_array[1,:]    # Rank 1 view 
print(row_rank1, row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [43]:
# Slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2,:]  # Rank 2 view 
print(row_rank2, row_rank2.shape)   # Notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [46]:
#We can do the same thing for columns of an array:

print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)  # Rank 1
print()
print(col_rank2, col_rank2.shape)  # Rank 2



[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>
Integer indexing:
</p>

This mechanism helps in selecting any arbitrary item in an array based on its N-dimensional index.
Each integer array represents the number of indexes into that dimension. 
It is like simple indexing but we pass arrays of indices in place of single scalars. 
This allows us to very quickly access and modify complicated subsets of an array's values. 


In [60]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
print(x[0,0], x[2,0], x[1,1]) #list of row = [0,1,2] , list of column=[0,0,1]

1 7 5


In [62]:
rows = [0,2,1]
column = [0,0,1]

In [65]:
x[rows,column]

array([1, 7, 5])

In [67]:
y = x[rows, column]         # selects the elements at (0,0), (1,1) and (2,0) 
print(y)

[1 7 5]


In [68]:
y[1] = 10

In [69]:
y

array([ 1, 10,  5])

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
x3

array([[[9, 9, 3, 2, 0],
        [5, 5, 1, 9, 2],
        [3, 3, 7, 1, 9],
        [0, 1, 2, 2, 5]],

       [[6, 0, 3, 5, 0],
        [9, 9, 8, 4, 6],
        [9, 2, 1, 7, 4],
        [7, 9, 0, 7, 8]],

       [[5, 3, 6, 6, 8],
        [7, 5, 7, 1, 2],
        [9, 8, 4, 0, 8],
        [2, 5, 1, 3, 5]]])

In [71]:
print(x3[0,0,0], x3[1,0,0], x3[2,0,0])

9 6 5


In [73]:
a = [0,1,2]
b = [0,0,0]
c = [0,0,0]

In [74]:
x3[a,b,c]

array([9, 6, 5])

### Exercise 2: Create a 3x3 array and write statements to retrieve its corner elements. 

In [76]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
x[0,0],x[0,2],x[2,0],x[2,2]

(1, 3, 7, 9)

In [78]:
r = [0,0,2,2] 
c = [0,2,0,2] 
a = x[r,c]
print(a)

[1 3 7 9]


In [82]:
rows = np.array([[0,0],[2,2]])
print(rows)
print('-----------')
cols = np.array([[0,2],[0,2]]) 
print(cols)
print('-----------')
y = x[rows,cols] 
print(y)                # prints the corner elements of the array. (0,0), (3,0) (0,2) and (3,2)

[[0 0]
 [2 2]]
-----------
[[0 2]
 [0 2]]
-----------
[[1 3]
 [7 9]]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold"><br>
Boolean Indexing

<br><br></p>
<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold"><br>

Array Indexing for changing elements:
</p>

In [1]:
import numpy as np

In [2]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [3]:
# create a filter which will be boolean values for whether each element meets this condition
filter1 = an_array < 15
filter1

array([[ True,  True],
       [False, False],
       [False, False]])

Notice that the filter is a same size ndarray as an_array which is filled with True for each element whose corresponding element in an_array which is greater than 15 and False for those elements whose value is less than 15.

In [6]:
# we can now select just those elements which meet that criteria
result=an_array[an_array < 15]
result

array([11, 12])

In [7]:
result[0]

11

In [8]:
result[0] = 100

In [9]:
result

array([100,  12])

In [10]:
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [11]:
# Filter values which are more than 20 and less than 30
res = (an_array>20) & (an_array<30)
print(res)

[[False False]
 [ True  True]
 [False False]]


In [12]:
a_slice = an_array[res]
print(a_slice)

[21 22]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold">
Array Operations
<br>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Arithmetic Array Operations:

</p>

In [13]:
import numpy as np

In [14]:
x = np.array([[1,2],[3,4]], dtype=np.int)
y = np.array([[1.0,2.0],[3.0,4.0]], dtype=np.float64)
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[1. 2.]
 [3. 4.]]


In [14]:
print('Addition : ')
print(x+y)
print('Subtraction : ')
print(x-y)
print('Multiplication : ')
print(x*y)
print('Division : ')
print(x/y)

Addition : 
[[2. 4.]
 [6. 8.]]
Subtraction : 
[[0. 0.]
 [0. 0.]]
Multiplication : 
[[ 1.  4.]
 [ 9. 16.]]
Division : 
[[1. 1.]
 [1. 1.]]


In [15]:
print(np.add(x,y))           # vectorized methods 
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[2. 4.]
 [6. 8.]]
[[0. 0.]
 [0. 0.]]
[[ 1.  4.]
 [ 9. 16.]]
[[1. 1.]
 [1. 1.]]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Element-wise Functions: </p>

For example, let's compare two arrays values to get the maximum of each.

In [16]:
# random array
x = np.random.randint(1,8,5)
x

array([1, 1, 6, 7, 1])

In [17]:
# another random array
y = np.random.randint(1,8,5)
y

array([7, 2, 5, 3, 4])

In [18]:
# returns element wise maximum between two arrays
print(np.maximum(x,y))
print(np.minimum(x,y))
print(np.equal(x,y))

[7 2 6 7 4]
[1 1 5 3 1]
[False False False False False]


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold">
Statistical Methods
<br>

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Basic Statistical Operations:
</p>

In [19]:
# setup a random 2 x 5 matrix
arr = np.random.randint(1,10,(2,5))
print(arr)
arr.shape

[[8 2 6 4 3]
 [3 3 6 7 4]]


(2, 5)

In [20]:
# compute the mean for all elements
print(arr.mean())

4.6


In [21]:
# compute the means by row
print(arr.mean(axis=1)) # axis 1 row selection , axis 0 column selection

[4.6 4.6]


In [22]:
# compute the means by column
print(arr.mean(axis=0))

[5.5 2.5 6.  5.5 3.5]


In [23]:
# sum all the elements
print(arr.sum())   # sum of all elements
print('columns sum is : ', arr.sum(axis=0))    # colsum
print('row sum is : ', arr.sum(axis=1))    # row sum

46
columns sum is :  [11  5 12 11  7]
row sum is :  [23 23]


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Finding Unique elements:
</p>

In [19]:
array = np.array([1,2,1,4,2,1,4,2,3])
print(array)

[1 2 1 4 2 1 4 2 3]


In [20]:
print(np.unique(array, return_counts=True))

(array([1, 2, 3, 4]), array([3, 3, 1, 2]))


<p style="font-family: Arial; font-size:2.75em;color:purple; font-style:bold">
Broadcasting:
<br>

Introduction to broadcasting. <br>
For more details, please see: <br>
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side. <br>

Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape. <br>

Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [2]:
import numpy as np

3d: (2, 3, 3) 2d: (2, 3)

2 * 2 * 3 #3d array
1 * 2 * 3 #2d array: padded 1 on left side its not a 3d array

Operation output: 2 * 2 * 3
    
#possibilities of 2d array shape: #*2*3 : 2*1 , 2*3, 1*3, 1*1

In [21]:
a1 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [22]:
print('shape of a1 : ',a1.shape)
print('dimension of a1 : ', a1.ndim)

shape of a1 :  (2, 2, 3)
dimension of a1 :  3


In [35]:
#2*1, 2*3, 1*3, 1*1
a2 = np.array([[10]])
print('shape of a2:',a2.shape)
print('dimension of a2:', a2.ndim)
print('array a2:', a2)

shape of a2: (1, 1)
dimension of a2: 2
array a2: [[10]]


In [36]:
a3 = a1+a2
print(a3)

[[[11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]]]


In [60]:
a3.shape

(2, 2, 3)

2d Array with 1d: <br>
(2, 3) + (3,) = True <br>
(2, 3) + (1,) = True

3d Array with 2d: <br>
(2,2,3) + (2,3) = True <br>
(2,2,3) + (2,1) = True <br>
(2,2,3) + (1,3) = True <br>
(2,2,3) + (1,1) = True <br>

In [14]:
start = np.zeros((4,3))
print(start) #4*3

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
add_cols = np.array([[1],[2],[3],[4]])
add_cols #4*1

array([[1],
       [2],
       [3],
       [4]])

In [18]:
start+add_cols

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [72]:
# this will just broadcast in both dimensions
add_scalar = np.array([5])
print(add_scalar)

[5]


In [73]:
print(start+add_scalar)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [87]:
arr = np.ones((3,2))
print(arr.shape)
print(arr) #3*2

(3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [93]:
arr2 = np.arange(5,10,2)#start, stop, interval
print(arr2.shape)
print(arr2) #3

(3,)
[5 7 9]


In [94]:
print(arr+arr2)

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Reshaping array:
</p>

In [2]:
import numpy as np

In [3]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
arr.shape

(20,)

In [7]:
# reshape to be a 4 x 5 matrix
new_arr = arr.reshape(2,2,5)
new_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [8]:
new_arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Indexing using where():</p>

In [9]:
x_1 = np.array([1,2,3,4,5,6])
y_1 = np.array([11,22,33,44,55,66])

In [10]:
for x,y in zip(x_1,y_1):
    if y%2!=0:
        print(y)
    else:
        print(x)

11
2
33
4
55
6


In [13]:
out = np.where(y_1%2!=0, y_1, x_1) # Condition , True Value, False Value
print(out)

[11  2 33  4 55  6]


In [11]:
mat = np.random.randint(1,10,25)
print(mat)
mat.reshape(5,5)

[7 2 4 9 3 9 1 7 3 3 8 6 9 4 2 2 8 4 9 8 4 3 9 5 9]


array([[7, 2, 4, 9, 3],
       [9, 1, 7, 3, 3],
       [8, 6, 9, 4, 2],
       [2, 8, 4, 9, 8],
       [4, 3, 9, 5, 9]])

In [12]:
np.where( mat > 5, True, False)

array([ True, False, False,  True, False,  True, False,  True, False,
       False,  True,  True,  True, False, False, False,  True, False,
        True,  True, False, False,  True, False,  True])

<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
"any" or "all" conditionals:</p>

In [14]:
arr_bools = np.array([True, False, True, True, False ])
b1 = np.array([True, True, True, True, True ])
b2 =  np.array([False, False, False, False, False])

In [15]:
print(arr_bools.any()) #Returns True if any value in array is True or else return False
print(b1.any()) 
print(b2.any()) 

True
True
False


In [17]:
print(arr_bools.all()) #Returns True if all value are True or else return False
print(b1.all())
print(b2.all())

False
True
False


<p style="font-family: Arial; font-size:1.75em;color:#2462C0; font-style:bold">
Merging and Spliting data sets:
</p>

In [27]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[28 21]
 [31 21]]

[[22 11]
 [46 19]]


In [28]:
np.vstack((K,M))

array([[28, 21],
       [31, 21],
       [22, 11],
       [46, 19]])

In [29]:
np.hstack((K,M))

array([[28, 21, 22, 11],
       [31, 21, 46, 19]])

In [110]:
np.concatenate([K, M], axis = 0) #vstack

array([[38, 12],
       [35, 24],
       [ 7, 35],
       [13,  4]])

In [112]:
np.concatenate([K, M], axis = 1) #hstack

array([[14, 10,  8, 48],
       [43, 28, 21, 49]])

In [41]:
A = np.random.randint(1,21,size=(4,4))
A

array([[16, 16, 10, 18],
       [ 2,  9, 16,  5],
       [ 1,  8, 13,  9],
       [12,  9, 18,  9]])

In [34]:
np.split(A,4,axis=0)

[array([[ 2, 16, 17, 17]]),
 array([[20,  1,  5,  5]]),
 array([[ 5,  5, 15,  3]]),
 array([[14, 18,  5, 20]])]

In [37]:
B = np.split(A,2,axis=1)
B

[array([[ 2, 16],
        [20,  1],
        [ 5,  5],
        [14, 18]]), array([[17, 17],
        [ 5,  5],
        [15,  3],
        [ 5, 20]])]

In [38]:
C = np.hsplit(A,4) #Divide columnwise axis=1
C

[array([[ 2],
        [20],
        [ 5],
        [14]]), array([[16],
        [ 1],
        [ 5],
        [18]]), array([[17],
        [ 5],
        [15],
        [ 5]]), array([[17],
        [ 5],
        [ 3],
        [20]])]

In [39]:
D = np.vsplit(A,4) #Divide row wise same as axis=0
D 

[array([[ 2, 16, 17, 17]]),
 array([[20,  1,  5,  5]]),
 array([[ 5,  5, 15,  3]]),
 array([[14, 18,  5, 20]])]